#Selectie gebaseerd op Referentie GrootboekSchema (RGS)
PREFIX vph-fin: <http://purl.org/ozo/vph-fin#>
PREFIX vph-g: <http://purl.org/ozo/vph-g#>

SELECT (SUM(?bedrag_personeel) AS ?noemer) (SUM(?bedrag_pnil) AS ?teller) (ROUND(?teller/?noemer*100) AS ?indicator)

WHERE { 
    {
	vph-fin:WPer vph-g:hasPart ?gb_personeel .
    ?gb_personeel vph-fin:heeftFinancieleBoeking ?boeking_personeel .
    ?boeking_personeel vph-fin:boekingsDatum ?datum ;
                       vph-fin:heeftFinancieleWaarde ?bedrag_personeel .
	} UNION {
	vph-fin:WBedOvpUik vph-g:hasPart ?gb_pnil .
    ?gb_pnil vph-fin:heeftFinancieleBoeking ?boeking_pnil .
    ?boeking_pnil vph-fin:boekingsDatum ?datum ;
                       vph-fin:heeftFinancieleWaarde ?bedrag_pnil .
	}
}