PREFIX vph-g: <http://purl.org/ozo/vph-g#>
PREFIX vph-pers: <http://purl.org/ozo/vph-pers#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (COUNT(DISTINCT(?vrijwilliger)) AS ?aantal_vrijwilligers)

WHERE {
    #Definieer periode
    BIND("2020-01-01"^^xsd:date AS ?start_periode)
    BIND("2020-12-31"^^xsd:date AS ?eind_periode)
    
    #Selecteer alle vrijwilligersovereenkomsten
    ?vrijwilliger a vph-g:Human ;
               vph-pers:heeftWerkOvereenkomst ?vrijwilligersovereenkomst .
    ?vrijwilligersovereenkomst a vph-pers:VrijwilligersOvereenkomst;
                               vph-pers:startDatum ?start_overeenkomst ;
                               vph-pers:eindDatum ?eind_overeenkomst .
    
    #Selecteer vrijwilligersovereenkomsten binnen gevraagde periode
    FILTER (?start_overeenkomst <= ?eind_periode && (!BOUND(?eind_overeenkomst) || ?eind_overeenkomst >= 
                ?start_periode))
}