PREFIX vph-g: <http://purl.org/ozo/vph-g#>
PREFIX vph-pers: <http://purl.org/ozo/vph-pers#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (COUNT(DISTINCT(?stagiaire)) AS ?aantal_stagiaires)

WHERE {
    #Definieer periode
    BIND("2020-01-01"^^xsd:date AS ?start_periode)
    BIND("2020-12-31"^^xsd:date AS ?eind_periode)
    
    #Selecteer alle stageovereenkomsten
    ?stagiaire a vph-g:Human ;
               vph-pers:heeftWerkOvereenkomst ?stageovereenkomst .
    ?stageovereenkomst a vph-pers:StageOvereenkomst;
                               vph-pers:startDatum ?start_overeenkomst ;
                               vph-pers:eindDatum ?eind_overeenkomst .
    
    #Selecteer stageovereenkomsten binnen gevraagde periode
    FILTER (?start_overeenkomst <= ?eind_periode && (!BOUND(?eind_overeenkomst) || ?eind_overeenkomst >= 
                ?start_periode))
}